Adjust `.schema_format=` API Usage for Rails 7 Compatibility (#128)
related: #126 

In Rails 7, the .schema_format= API is moved from ActiveRecord::Base to
ActiveRecord
- ref: https://github.com/rails/rails/pull/42445

It also solved the following CI failure.
```    
NoMethodError: undefined method `schema_format=' for ActiveRecord::Base:Class
```